table dim_product

	column product_key
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column sub_category
		dataType: string
		summarizeBy: none
		sourceColumn: sub_category

		annotation SummarizationSetBy = Automatic

	partition dim_product = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("127.0.0.1", "ecommerce"),
				    Data = Source{[Schema="core",Item="dim_product"]}[Data],
				    Typed = Table.TransformColumnTypes(Data, {{"product_key", Int64.Type},{"product_id", type text},{"product_name", type text},{"category", type text},{"sub_category", type text}})
				in
				    Typed

	annotation PBI_ResultType = Table
