table dim_date
	dataCategory: Time

	column date_key
		dataType: dateTime
		isKey
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter_no
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: quarter_no

		annotation SummarizationSetBy = Automatic

	column quarter_name
		dataType: string
		summarizeBy: none
		sourceColumn: quarter_name
		sortByColumn: quarter_no

		annotation SummarizationSetBy = Automatic

	column year_quarter
		dataType: string
		summarizeBy: none
		sourceColumn: year_quarter

		annotation SummarizationSetBy = Automatic

	column month_no
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: month_no

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month_no

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column month_index
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: month_index

		annotation SummarizationSetBy = Automatic

	column day_of_month
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: day_of_month

		annotation SummarizationSetBy = Automatic

	column day_of_week_no
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: day_of_week_no

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: string
		summarizeBy: none
		sourceColumn: day_of_week
		sortByColumn: day_of_week_no

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column month_start
		dataType: dateTime
		isHidden
		summarizeBy: none
		sourceColumn: month_start

		annotation SummarizationSetBy = Automatic

	column month_end
		dataType: dateTime
		isHidden
		summarizeBy: none
		sourceColumn: month_end

		annotation SummarizationSetBy = Automatic

	column quarter_start
		dataType: dateTime
		isHidden
		summarizeBy: none
		sourceColumn: quarter_start

		annotation SummarizationSetBy = Automatic

	column year_start
		dataType: dateTime
		isHidden
		summarizeBy: none
		sourceColumn: year_start

		annotation SummarizationSetBy = Automatic

	column is_latest_year
		dataType: boolean
		isHidden
		summarizeBy: none
		sourceColumn: is_latest_year

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("127.0.0.1", "ecommerce"),
				    Data = Source{[Schema="core",Item="dim_date"]}[Data],
				    Typed = Table.TransformColumnTypes(Data, {{"date_key", type date},{"year", Int64.Type},{"quarter_no", Int64.Type},{"quarter_name", type text},{"year_quarter", type text},{"month_no", Int64.Type},{"month_name", type text},{"year_month", type text},{"month_index", Int64.Type},{"day_of_month", Int64.Type},{"day_of_week_no", Int64.Type},{"day_of_week", type text},{"is_weekend", type logical},{"month_start", type date},{"month_end", type date},{"quarter_start", type date},{"year_start", type date},{"is_latest_year", type logical}})
				in
				    Typed

	annotation PBI_ResultType = Table
