table dim_geography

	column geography_key
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: geography_key

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		summarizeBy: none
		sourceColumn: city
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column postal_code
		dataType: string
		summarizeBy: none
		sourceColumn: postal_code
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	partition dim_geography = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("127.0.0.1", "ecommerce"),
				    Data = Source{[Schema="core",Item="dim_geography"]}[Data],
				    Typed = Table.TransformColumnTypes(Data, {{"geography_key", Int64.Type},{"country", type text},{"region", type text},{"state", type text},{"city", type text},{"postal_code", type text}})
				in
				    Typed

	annotation PBI_ResultType = Table
