table fact_return

	column order_id
		dataType: string
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: dateTime
		isHidden
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column customer_key
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: customer_key

		annotation SummarizationSetBy = Automatic

	column geography_key
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: geography_key

		annotation SummarizationSetBy = Automatic

	column order_lines
		dataType: int64
		formatString: #,0
		isHidden
		summarizeBy: sum
		sourceColumn: order_lines

		annotation SummarizationSetBy = Automatic

	column order_sales
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		isHidden
		summarizeBy: sum
		sourceColumn: order_sales

		annotation SummarizationSetBy = Automatic

	column order_profit
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		isHidden
		summarizeBy: sum
		sourceColumn: order_profit

		annotation SummarizationSetBy = Automatic

	column order_quantity
		dataType: int64
		formatString: #,0
		isHidden
		summarizeBy: sum
		sourceColumn: order_quantity

		annotation SummarizationSetBy = Automatic

	column return_status
		dataType: string
		summarizeBy: none
		sourceColumn: return_status

		annotation SummarizationSetBy = Automatic

	partition fact_return = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("127.0.0.1", "ecommerce"),
				    Data = Source{[Schema="core",Item="fact_return"]}[Data],
				    Typed = Table.TransformColumnTypes(Data, {{"order_id", type text},{"date_key", type date},{"customer_key", Int64.Type},{"geography_key", Int64.Type},{"order_lines", Int64.Type},{"order_sales", Currency.Type},{"order_profit", Currency.Type},{"order_quantity", Int64.Type},{"return_status", type text}})
				in
				    Typed

	annotation PBI_ResultType = Table
